# Generated by Django 4.0.1 on 2022-03-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='ipaddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='adnin',
            new_name='admin',
        ),
    ]
